pipeline{
    agent any
    stages{
        stage ('install dependisis'){
            steps{
                bat """
                    cd automation_exercise
                    C:\\Users\\yanam\\AppData\\Local\\Programs\\Python\\Python313\\python.exe -m pip install -r requirements.txt
                    docker build -t leela .
                    """
                    }}
        stage('Run_test'){
            steps {
                bat """
                    cd automation_exercise
                    C:\\Users\\yanam\\AppData\\Local\\Programs\\Python\\Python313\\python.exe -m pytest -v 
                    
                    """
                }   
            }
        }    
    post{
        always{
            publishHTML([
            allowMissing:false,
            alwaysLinkToLastBuild:true,
            keepAll:true,
            reportDir:'Project2/reports',
            reportFiles:'report.html',
            reportName:'Pytest Html Report'])
                
            }
        }
    } 
   
        